name: update

on:
  schedule:
    - cron: '13,43 * * * *'

jobs:
  perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Install perl
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/relocatable-perl/main/perl-install | bash -s ~/perl
      - name: Install deps
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | ~/perl/bin/perl - install -g --cpmfile maint/cpm.yml --show-build-log-on-failure
      - name: Execute generate.pl
        run: ~/perl/bin/perl maint/generate.pl > perl-releases.v1.csv.new
      - name: Update if necessary
        run: bash maint/update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
