name: update

on:
  schedule:
    - cron: '25,55 * * * *'

jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: curl -fsSL --compressed https://git.io/cpm | perl - install -g --cpanfile maint/cpanfile --show-build-log-on-failure
      - name: Execute generate.pl
        run: perl maint/generate.pl > perl-releases.v1.csv.new
      - name: Update if necessary
        run: bash maint/update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
